# Generated by Django 4.0.5 on 2022-06-20 06:51

import django.contrib.auth.models
import django.contrib.postgres.fields.citext
from django.db import migrations, models
from django.contrib.postgres.operations import CITextExtension

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        CITextExtension(),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', django.contrib.postgres.fields.citext.CICharField(error_messages={'unique': 'Данное имя уже занято. Пожалуйста, выберите другое.'}, max_length=15, unique=True, verbose_name='Username')),
                ('email', django.contrib.postgres.fields.citext.CIEmailField(error_messages={'unique': 'Адрес электронной почты уже занят.'}, max_length=255, unique=True, verbose_name='Email')),
                ('profile_name', models.CharField(max_length=50, verbose_name='Имя профиля')),
                ('about', models.CharField(blank=True, max_length=160, verbose_name='О себе')),
                ('location', models.CharField(blank=True, max_length=30, verbose_name='Местоположение')),
                ('website', models.URLField(blank=True, max_length=100, verbose_name='Веб-сайт')),
                ('date_of_birth', models.DateField()),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
